# Generated by Django 3.1.14 on 2022-01-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0008_multi_repo_support_final"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="backup_match_rule",
        ),
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="intended_match_rule",
        ),
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="backup_repository",
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="backup_repository",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"provided_contents__contains": "nautobot_golden_config.backupconfigs"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backup_repository",
                to="extras.gitrepository",
            ),
        ),
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="intended_repository",
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="intended_repository",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"provided_contents__contains": "nautobot_golden_config.intendedconfigs"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intended_repository",
                to="extras.gitrepository",
            ),
        ),
    ]
