# Generated by Django 3.1.14 on 2022-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0009_auto_20220112_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="name",
            field=models.CharField(default="defaults", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="slug",
            field=models.SlugField(default="defaults", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
