# Generated by Django 3.1.14 on 2022-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0010_auto_20220117_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
