# Generated by Django 3.1.14 on 2022-01-19 14:11

from django.db import migrations, models
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0011_goldenconfigsetting_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldenconfigsetting",
            options={"ordering": ["weight", "name"], "verbose_name": "Golden Config Setting"},
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="weight",
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
