# Generated by Django 3.1.14 on 2022-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0012_auto_20220119_1411"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldenconfigsetting",
            options={"ordering": ["-weight", "name"], "verbose_name": "Golden Config Setting"},
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
